// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb437_8OYJPDGuf_YonX7ok79kQHN4D-o',
    appId: '1:706670451198:web:530ac91a9bb980e3d688af',
    messagingSenderId: '706670451198',
    projectId: 'fir-02-a1395',
    authDomain: 'fir-02-a1395.firebaseapp.com',
    storageBucket: 'fir-02-a1395.appspot.com',
    measurementId: 'G-QL84D7819Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt-axk7XqGEhcWF_nLFagJ2K1clIqWNeo',
    appId: '1:706670451198:android:333b8770d486e7a4d688af',
    messagingSenderId: '706670451198',
    projectId: 'fir-02-a1395',
    storageBucket: 'fir-02-a1395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_EIfCmm2DsI-p4rNM1LZfAnuAlgjf8a4',
    appId: '1:706670451198:ios:855cd96ad61a2c90d688af',
    messagingSenderId: '706670451198',
    projectId: 'fir-02-a1395',
    storageBucket: 'fir-02-a1395.appspot.com',
    iosBundleId: 'com.example.noteTaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_EIfCmm2DsI-p4rNM1LZfAnuAlgjf8a4',
    appId: '1:706670451198:ios:855cd96ad61a2c90d688af',
    messagingSenderId: '706670451198',
    projectId: 'fir-02-a1395',
    storageBucket: 'fir-02-a1395.appspot.com',
    iosBundleId: 'com.example.noteTaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb437_8OYJPDGuf_YonX7ok79kQHN4D-o',
    appId: '1:706670451198:web:73fff792edf97720d688af',
    messagingSenderId: '706670451198',
    projectId: 'fir-02-a1395',
    authDomain: 'fir-02-a1395.firebaseapp.com',
    storageBucket: 'fir-02-a1395.appspot.com',
    measurementId: 'G-6ZNGR6P4T9',
  );
}
